# Generated by Django 5.1.4 on 2025-05-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnergyManageRank",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("call_time", models.IntegerField(default=0)),
                ("call_rank", models.IntegerField(default=0)),
                (
                    "soc",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("soc_rank", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "能量管理排名",
                "db_table": "energy_manage_rank",
            },
        ),
    ]
