# Generated by Django 5.1.4 on 2025-05-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EnergyManagement", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="energymanagerank",
            old_name="call_rank",
            new_name="charge_time",
        ),
        migrations.RenameField(
            model_name="energymanagerank",
            old_name="soc_rank",
            new_name="discharge_time",
        ),
        migrations.AddField(
            model_name="energymanagerank",
            name="recent_30days",
            field=models.IntegerField(default=0),
        ),
    ]
