# Generated by Django 5.1.4 on 2025-05-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "EnergyManagement",
            "0002_rename_call_rank_energymanagerank_charge_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="energymanagerank",
            name="call_time",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="energymanagerank",
            name="charge_time",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="energymanagerank",
            name="discharge_time",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="energymanagerank",
            name="recent_30days",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="energymanagerank",
            name="soc",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=5, null=True
            ),
        ),
    ]
