# Generated by Django 5.1.4 on 2025-04-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PieDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_time", models.DateTimeField(auto_now_add=True)),
                ("partition1", models.FloatField()),
                ("partition2", models.FloatField()),
                ("partition3", models.FloatField()),
                ("partition4", models.FloatField()),
                ("partition5", models.FloatField()),
                ("analysis_type", models.CharField(default="day", max_length=10)),
                (
                    "pie_type",
                    models.CharField(
                        choices=[
                            ("Soc_distribution", "Soc distribution"),
                            ("Frequency_Distribution", "Frequency Distribution"),
                            ("Duration_distribution", "Duration Distribution"),
                        ],
                        max_length=40,
                    ),
                ),
            ],
            options={
                "db_table": "PieDataDistribution",
            },
        ),
    ]
