# Generated by Django 5.1.4 on 2025-04-09 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showcenter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="piedistribution",
            table="Pie_Data_Distribution",
        ),
    ]
