# Generated by Django 5.1.4 on 2025-05-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcenter", "0002_alter_piedistribution_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunStatisticsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataA", models.IntegerField(default=0)),
                ("dataB", models.IntegerField(default=0)),
                ("dataC", models.IntegerField(default=0)),
                ("dataD", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "运行统计数据",
                "db_table": "running_statistics_data",
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="piedistribution",
            options={"ordering": ["-analysis_time"], "verbose_name": "首页饼图数据"},
        ),
        migrations.AlterField(
            model_name="piedistribution",
            name="partition1",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="piedistribution",
            name="partition2",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="piedistribution",
            name="partition3",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="piedistribution",
            name="partition4",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="piedistribution",
            name="partition5",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
